In [5]:
import numpy as np

# Example: three separate 2D arrays
arr1 = np.ones((4, 5))
arr2 = np.ones((4, 5)) * 2
arr3 = np.ones((4, 5)) * 3

# Stack them along the last axis (axis=-1)
# The resulting shape will be (4, 5, 3)
stacked_arr = np.stack([arr1, arr2, arr3], axis=0)

print(f"Stacked shape: {stacked_arr.shape}")
print(stacked_arr[0, 0, :]) # Example element: [1. 2. 3.]

Stacked shape: (3, 4, 5)
[1. 1. 1. 1. 1.]


In [6]:
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
print(stacked_arr)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]]
